************************************
*** DroneControl is initialized! ***
************************************
(error(111, 'Connection refused'), 'sleeping')
(error(111, 'Connection refused'), 'sleeping')
Traceback (most recent call last):
  File "../drone-server/server.py", line 13, in <module>
    drone = DroneControl("tcp:127.0.0.1:5760", 57600, "localhost", 7000, 12)
  File "../drone-lib/dronecontrol.py", line 32, in __init__
    self.conn(droneHost, droneBaud)
  File "../drone-lib/dronecontrol.py", line 51, in conn
    self.vehicle = connect(host, baud=baud, wait_ready=True)
  File "/usr/local/lib/python2.7/dist-packages/dronekit/__init__.py", line 2817, in connect
    handler = MAVConnection(ip, baud=baud, source_system=source_system, use_native=use_native)
  File "/usr/local/lib/python2.7/dist-packages/dronekit/mavlink.py", line 128, in __init__
    self.master = mavutil.mavlink_connection(ip, baud=baud, source_system=source_system)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/mavutil.py", line 1203, in mavlink_connection
    return mavtcp(device[4:], source_system=source_system, retries=retries, use_native=use_native)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/mavutil.py", line 941, in __init__
    self.port.connect(self.destination_addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
